// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Let = 3,
  Ident = 4,
  _let = 5,
  PipeExpr = 6,
  App = 7,
  Number = 8,
  String = 9,
  List = 10,
  ParenArith = 11,
  ArithOp = 12,
  OpDef = 13,
  op = 14,
  Preload = 15,
  preload = 16,
  as = 17
