// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Ident = {__proto__:null,let:10, op:28, preload:32, as:34}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'[QYQPOOO!VQPO'#CfOtQPO'#CzOOQO'#Cz'#CzO!oQPO'#CzOOQO'#Cy'#CyO#`QPO'#CuOOQO'#Cw'#CwOOQO'#Cu'#CuO#hQPO'#CnQYQPOOO#mQPO'#C_O#rQPO'#CiO#wQPO'#CkO#|QPO'#DPOOQO,59Q,59QO$XQPO,59QO$^QPO,59fOOQO'#Co'#CoO$rQPO,58}OtQPO,58|OOQO,59Y,59YOOQO-E6l-E6lO%cQPO,58yO%hQPO,59TO%pQPO,59VOtQPO'#CpO%xQPO,59kOOQO1G.l1G.lOOQO'#Ch'#ChOtQPO1G.mOOQO1G/Q1G/QOOQO-E6m-E6mOOQO1G.h1G.hOtQPO1G.eOOQO'#Cq'#CqO&QQPO'#DVO&YQPO1G.oO&_QPO1G.qO&dQPO,59[OOQO-E6n-E6nO&oQPO7+$XO&wQPO7+$POOQO-E6o-E6oOtQPO7+$ZOOQO7+$]7+$]OOQO<<Gs<<GsO'PQPO<<Gu",
  stateData: "'`~OhOSPOS~OSSOTZOWROXRO^[O`]OoQOrPO~OSSOWROXROoQOrPO~Oq_O~PtOSROWROXROoQOrPO~OlnXznXqnXtnXpnXunXvnXwnXxnX~P!^OldOziX~OzeO~OSgO~OShO~OXiO~OldOtjOqsX~OqlO~OldOpoOumOvmOwmOxmO~OlVazVaqVatVapVauVavVawVaxVa~P!^OjrO~OSsOjyP~OavOz_a~OtjOqsa~OSsOjyX~Oj|O~OX}O~OldOqdatda~OldOp!OO~OldOzRq~OldOz]y~OPvWShW~",
  goto: "$nzPPP{PP!P!ZPP!f!f!s{P{PP!v!|#S#YPPP#`P#dP#z$XPPPP$hPPPPP$kTWOYaVOPQYjnr|cTOPQYdjnr|gROPQSYcdjnr|RnaQYORfYQcSRpcQk^RxkQthR{tTXOYSUOYQ^PQaQQwjQynQzrR!P|`VOPQYjnr|RqdbTOPQYdjnr|TbScR`PRuh",
  nodeNames: "⚠ LineComment Program Let Ident let PipeExpr App Number String List ParenArith ArithOp OpDef op Preload preload as",
  maxTerm: 42,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "'X~RcXY!^YZ!^pq!^wx!lxy$Yyz$_z{$d{|$i|}$n}!O$s!P!Q&Q!Q![%g!]!^&V!_!`&[!c!}&a!}#O&r#P#Q&w#T#o&a#p#q&|~!cRh~XY!^YZ!^pq!^~!oVOw!lwx#Ux#O!l#O#P#Z#P;'S!l;'S;=`$S<%lO!l~#ZOX~~#^RO;'S!l;'S;=`#g;=`O!l~#jWOw!lwx#Ux#O!l#O#P#Z#P;'S!l;'S;=`$S;=`<%l!l<%lO!l~$VP;=`<%l!l~$_Oo~~$dOp~~$iOw~~$nOu~~$sOt~~$xQv~}!O%O!Q![%g~%TSP~OY%OZ;'S%O;'S;=`%a<%lO%O~%dP;=`<%l%O~%lQW~!O!P%r!Q![%g~%uP!Q![%x~%}PW~!Q![%x~&VOx~~&[Oz~~&aOj~~&fSS~!Q![&a!c!}&a#R#S&a#T#o&a~&wOr~~&|Oq~~'PP!`!a'S~'XOl~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Ident[value] || -1}],
  tokenPrec: 285
})
